<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>KeepAwake</AssemblyName>
    <RootNamespace>KeepAwake</RootNamespace>
    <ApplicationIcon>KeepAwake.ico</ApplicationIcon>

    <Version>1.0.1</Version>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
    <Product>KeepAwake</Product>
  </PropertyGroup>

</Project>